name: 'Publish Quartz'
description: 'Convert Logseq graph to a fast, static Quartz website. Generates individual HTML pages instead of SPA.'
author: 'cyberia-to'

branding:
  icon: 'book-open'
  color: 'green'

inputs:
  graph-path:
    description: 'Path to Logseq graph (default: current directory)'
    required: false
    default: '.'
  output-path:
    description: 'Output directory for built site'
    required: false
    default: 'public'
  quartz-version:
    description: 'Quartz version to use'
    required: false
    default: 'v4'
  home:
    description: 'Override home page (from config.edn :default-home)'
    required: false
  title:
    description: 'Override site title (from config.edn :meta/title)'
    required: false
  favorites:
    description: 'Comma-separated favorites list (overrides config.edn :favorites)'
    required: false
  site-name:
    description: 'Site name for meta tags'
    required: false

outputs:
  output-path:
    description: 'Path to the generated site'
    value: ${{ inputs.output-path }}

runs:
  using: 'composite'
  steps:
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '22'

    - name: Setup Rust
      uses: dtolnay/rust-toolchain@stable

    - name: Cache Rust dependencies
      uses: actions/cache@v4
      with:
        path: |
          ~/.cargo/bin/
          ~/.cargo/registry/
          ~/.cargo/git/
          ${{ github.action_path }}/preprocessor/target/
        key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

    - name: Clone Quartz
      shell: bash
      run: |
        git clone --depth 1 https://github.com/jackyzha0/quartz.git quartz-build
        cd quartz-build && npm ci

    - name: Build preprocessor
      shell: bash
      run: |
        cd ${{ github.action_path }}/preprocessor
        cargo build --release

    - name: Preprocess Logseq content
      shell: bash
      run: |
        PREPROCESS_CMD="${{ github.action_path }}/preprocessor/target/release/logseq-to-quartz \
          --input ${{ inputs.graph-path }} \
          --output quartz-build/content \
          --create-stubs"
        if [ -n "${{ inputs.home }}" ]; then
          PREPROCESS_CMD="$PREPROCESS_CMD --home \"${{ inputs.home }}\""
        fi
        if [ -n "${{ inputs.title }}" ]; then
          PREPROCESS_CMD="$PREPROCESS_CMD --title \"${{ inputs.title }}\""
        fi
        if [ -n "${{ inputs.favorites }}" ]; then
          PREPROCESS_CMD="$PREPROCESS_CMD --favorites \"${{ inputs.favorites }}\""
        fi
        if [ -n "${{ inputs.site-name }}" ]; then
          PREPROCESS_CMD="$PREPROCESS_CMD --site-name \"${{ inputs.site-name }}\""
        fi
        eval $PREPROCESS_CMD

    - name: Copy theme customizations
      shell: bash
      run: |
        THEME_DIR="${{ github.action_path }}/quartz-theme"
        cp "$THEME_DIR/quartz.config.ts" quartz-build/
        cp "$THEME_DIR/quartz.layout.ts" quartz-build/
        cp "$THEME_DIR/styles/custom.scss" quartz-build/quartz/styles/
        cp "$THEME_DIR/path.ts" quartz-build/quartz/util/
        # Components
        cp "$THEME_DIR/components/"*.tsx quartz-build/quartz/components/
        cp "$THEME_DIR/components/components-index.ts" quartz-build/quartz/components/index.ts
        # Scripts and styles
        cp "$THEME_DIR/scripts/"*.ts quartz-build/quartz/components/scripts/
        cp "$THEME_DIR/styles/"*.scss quartz-build/quartz/components/styles/

    - name: Apply site configuration
      shell: bash
      run: |
        # Read site config generated by preprocessor
        if [ -f "quartz-build/content/_site_config.json" ]; then
          PAGE_TITLE=$(cat quartz-build/content/_site_config.json | jq -r '.page_title')
          SITE_NAME=$(cat quartz-build/content/_site_config.json | jq -r '.site_name // empty')
          echo "Applying site title: $PAGE_TITLE"
          # Update pageTitle in quartz.config.ts
          sed -i "s/pageTitle: \"Cyber\"/pageTitle: \"$PAGE_TITLE\"/" quartz-build/quartz.config.ts
          # Update site name in meta tags if provided
          if [ -n "$SITE_NAME" ]; then
            echo "Applying site name: $SITE_NAME"
            sed -i "s/og:site_name\" content=\"[^\"]*\"/og:site_name\" content=\"$SITE_NAME\"/" quartz-build/quartz.config.ts 2>/dev/null || true
          fi
        fi

    - name: Build Quartz site
      shell: bash
      run: |
        cd quartz-build
        npx quartz build -o ../${{ inputs.output-path }}
